### ISSUE TITLE
doesn't seem to be working

### ISSUE THREAD

**Issue by USMP-lancer** [FLSoz/LaserMod#1]
unsure exactly why its just not overriding the lasers

**Comment by FLSoz** [comment]
Root cause was you didn't enable BlockInjector.
I've added it to the requirements list so TTMM should auto-enable it when you enable LaserMod in the future.
Reopening this issue briefly to comment that you'll need to manually enable Block Injector (Or disable, update, then re-enable LaserMod) in TTMM since I'm pretty sure it only enforces dependencies the first time you enable a mod.

If you're going to open a github issue, please do me the courtesy of opening the output log and copy-pasting the error.
On windows, output log is at: C:/Users/$USER$/AppData/LocalLow/Payload/TerraTech/output_log.txt

**Comment by USMP-lancer** [comment]
oh im just very cool and smart lol
